duckyware/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('cart/', views.cart, name='cart'),
    path('search/', views.search, name='search'),
    path("logout", views.logout_view, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("orders/", views.orders, name="orders"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path('update_account_info/', views.update_account_info, name='update_account_info'),
    path('edit-shipping-address/', views.edit_shipping_address, name='edit_shipping_address'),
    path('change_password/', views.change_password, name='change_password'),
    path('category/<str:category_name>/', views.category, name='category'),
    path('error/', views.error_page, name='error_page'),
    path('category/<str:category_name>/product/<int:product_id>/', views.product_view, name='product_view'),
    path('add_to_wishlist/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('get-cart-quantity/', views.get_cart_quantity, name='get_cart_quantity'),
    path('cart/', views.cart, name='cart'),
    path('update_cart_item/', views.update_cart_item, name='update_cart_item'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('remove_cart_item/', views.remove_cart_item, name='remove_cart_item'),
    path('process-payment/', views.process_payment, name='process_payment'),
    path('payment/execute/', views.payment_execute, name='payment_execute'),
    path("payment/", views.paypal_payment, name="paypal_payment"),
    path("credit_card/", views.credit_card_payment, name="credit_card_payment"),
    path("transfer/", views.transfer_payment, name="transfer_payment"),
    path('credit-card/execute/', views.credit_card_execute, name='credit_card_execute'),
    path('orders/<int:order_id>/', views.order_detail, name='order_detail'),
]

store/models/base_models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    phone = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.user.username


class ShippingAddress(models.Model):
    profile = models.ForeignKey(UserProfile, related_name="shipping_addresses", on_delete=models.CASCADE)
    recipient_name = models.CharField(max_length=100, verbose_name="Recipient Name", default="Unknown Recipient")
    full_address = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=20)
    country = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.recipient_name} - {self.full_address}, {self.city}, {self.zip_code}, {self.country}"

    class Meta:
        unique_together = ('profile', 'city', 'zip_code', 'country', 'recipient_name')


class Category(models.Model):
    name = models.CharField(max_length=100)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class Meta:
        unique_together = ('name', 'parent',)
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    stock_quantity = models.PositiveIntegerField(default=0)
    discounted_units = models.IntegerField(default=0)
    units_sold = models.PositiveIntegerField(default=0)

    def average_rating(self):
        reviews = self.reviews.all()
        if reviews:
            return sum(review.rating for review in reviews) / reviews.count()
        else:
            return 0

    class Meta:
        abstract = True 

    def __str__(self):
        return self.name


class CartItem(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    session_key = models.CharField(max_length=40, null=True, blank=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.content_object} x{self.quantity}'


class Order(models.Model):
    ORDER_STATUS_CHOICES = [
        ('CONFIRMING_PAYMENT', 'Confirming Payment'),
        ('PREPARING', 'Preparing'),
        ('AWAITING_PICKUP', 'Awaiting Pickup'),
        ('EN_ROUTE', 'En Route'),
        ('DELIVERED', 'Delivered'),
    ]
    
    PAYMENT_METHOD_CHOICES = [
        ('PAYPAL', 'PayPal'),
        ('CREDIT_CARD', 'Credit Card'),
        ('TRANSFER', 'Transfer'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    shipping_address = models.TextField(verbose_name="Shipping Address")
    shipping_city = models.CharField(max_length=100, verbose_name="Shipping City")
    status = models.CharField(max_length=20, choices=ORDER_STATUS_CHOICES, default='CONFIRMING_PAYMENT', verbose_name="Order Status")
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES, default='PAYPAL',verbose_name="Payment Method")
    bank_account_number = models.CharField(max_length=30, blank=True, null=True, verbose_name="Bank Account Number")

    def __str__(self):
        return f'Order {self.id} by {self.user.username}'
    
    def save(self, *args, **kwargs):
        if self.payment_method == 'TRANSFER':
            self.bank_account_number = '1234567890'  # Example bank account number
        else:
            self.bank_account_number = None
        super().save(*args, **kwargs)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    quantity = models.PositiveIntegerField(default=1)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    price_at_purchase = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.content_object} x{self.quantity} in order {self.order.id}'


class ProductImage(models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    product = GenericForeignKey('content_type', 'object_id')
    image = models.ImageField(upload_to='product_images/')

    def __str__(self):
        return f"Image for {self.product}"


class Review(models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    product = GenericForeignKey('content_type', 'object_id')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.TextField()
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Review by {self.user.username} on {self.product}"


store/forms.py
# store/forms.py

from django import forms
from .models import ShippingAddress

class ShippingAddressForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields = ['recipient_name', 'full_address', 'city', 'zip_code', 'country']

store/templates/store/cart.html
{% extends 'store/layout.html' %}
{% load custom_filters %}

{% block content %}
<div class="container mt-4 mb-4">
    <h1 class="text-center">Your Cart</h1>
    {% if not order_items %}
        <br><br>
        <p>Your cart is empty.</p>
    {% else %}
        <br><br>
        <div class="cart-items">
            <div class="row">
                <div class="col-12">
                    <div class="cart-header">
                        <div class="row">
                            <div class="col-md-7 col-sm-6"><h4>Product</h4></div>
                            <div class="col-md-1 col-sm-2"><h4>Quantity</h4></div>
                            <div class="col-md-1 col-sm-2"></div>
                            <div class="col-md-1 col-sm-2"><h4>Price</h4></div>
                            <div class="col-md-1 col-sm-2"><h4>Subtotal</h4></div>
                            <div class="col-md-1 col-sm-2"></div>
                        </div>
                    </div>
                    {% for item in order_items %}
                    <div class="cart-item">
                        <div class="row align-items-start">
                            <div class="col-md-7 col-sm-6">
                                <div class="cart-product-name"><a href="{% url 'store:product_view' category_name=item.content_object.category.name product_id=item.content_object.id %}" class="product-link">
                                    {{ item.content_object.title }}
                                </a></div>
                            </div>
                            <div class="col-md-1 col-sm-2">
                                <input type="number" class="form-control quantity-input" value="{{ item.quantity }}" min="1" max="{{ item.max_units }}" data-item-id="{{ item.id }}">
                            </div>
                            <div class="col-md-1 col-sm-2"></div>
                            <div class="col-md-1 col-sm-2">
                                <div class="cart-price">${{ item.price|floatformat:2 }}</div>
                            </div>
                            <div class="col-md-1 col-sm-2">
                                <div class="cart-total">${{ item.quantity|multiply:item.price|floatformat:2 }}</div>
                            </div>
                            <div class="col-md-1 col-sm-2">
                                <button class="btn btn-outline-danger btn-sm" data-item-id="{{ item.id }}">Delete</button>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <br>
                    <div class="cart-footer">
                        <div class="row">
                            <div class="col-md-8 col-sm-6 text-end"><h4>Total:</h4></div>
                            <div class="col-md-2 col-sm-3"></div>
                            <div class="col-md-2 col-sm-3"><h4>${{ cart_total|floatformat:2 }}</h4></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="cart-actions mt-4 text-center">
            <div class="row">
                <div class="col-md-8 col-sm-6"></div>
                <div class="col-md-2 col-sm-3">
                    <button id="clear-cart-button" class="btn btn-danger btn-sm">Clear Cart</button>
                </div>
                <div class="col-md-2 col-sm-3">
                    <a href="{% url 'store:checkout' %}" class="btn btn-outline-secondary btn-sm">Proceed to Checkout</a>
                </div>
            </div>
        </div>       
    {% endif %}
</div>
{% endblock %}







store/templates/store/checkout.html
{% extends 'store/layout.html' %}
{% load custom_filters %}

{% block content %}
<div class="container mt-4 mb-4">
    <div class="row">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        
        <!-- Left Side: List of Products -->
        <div class="col-md-9">
            <h2>Review Your Order</h2>
            <br>
            <div class="cart-items">
                <div class="cart-header">
                    <div class="row">
                        <div class="col-md-7"><h4>Product</h4></div>
                        <div class="col-md-1"><h4>Quantity</h4></div>
                        <div class="col-md-1"></div>
                        <div class="col-md-1"><h4>Price</h4></div>
                        <div class="col-md-1"><h4>Subtotal</h4></div>
                        <div class="col-md-1"></div>
                    </div>
                </div>
                {% for item in order_items %}
                <div class="cart-item">
                    <div class="row align-items-start">
                        <div class="col-md-7">
                            <div class="cart-product-name">
                                <a href="{% url 'store:product_view' category_name=item.content_object.category.name product_id=item.content_object.id %}" class="product-link">
                                    {{ item.content_object.title }}
                                </a>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="cart-quantity">{{ item.quantity }}</div>
                        </div>
                        <div class="col-md-1"></div>
                        <div class="col-md-1">
                            <div class="cart-price">${{ item.price }}</div>
                        </div>
                        <div class="col-md-1">
                            <div class="cart-total">${{ item.quantity|multiply:item.price }}</div>
                        </div>
                        <div class="col-md-1"></div>
                    </div>
                </div>
                {% endfor %}
                <br>
                <div class="cart-footer">
                    <div class="row">
                        <div class="col-md-8 text-end"><h4>Total:</h4></div>
                        <div class="col-md-2"></div>
                        <div class="col-md-2"><h4>${{ cart_total }}</h4></div>
                    </div>
                </div>
            </div>
        </div>

        
        <!-- Right Side: Shipping Information -->
        <div class="col-md-3">
            {% if user.is_authenticated %}
                {% if shipping_address %}
                    <h2>Shipping Address</h2>
                    <br>
                    <p>{{ shipping_address.recipient_name }}</p>
                    <p>{{ shipping_address.full_address }}</p>
                    <p>{{ shipping_address.city }}, {{ shipping_address.zip_code }}</p>
                    <p>{{ shipping_address.country }}</p>
                    <div class="checkout-action mt-4 text-center">
                        <form id="paymentForm" method="post" action="{% url 'store:process_payment' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <select class="form-select" name="payment_method" id="payment_method" required>
                                    <option value="1" disabled selected>Select Payment Method</option>
                                    <option value="credit_card">Credit Card</option>
                                    <option value="paypal">PayPal</option>
                                    <option value="transfer">Transfer</option>
                                </select>
                            </div>
                            <button type="submit" class="btn btn-outline-secondary btn-lg mt-4" id="proceedToPaymentButton">Proceed to Payment</button>
                        </form>
                    </div>

                    <div class="mt-4">
                        <h5>PayPal Sandbox Testing Information</h5>
                        <p>To test the PayPal payment method, you can use the following sandbox accounts:</p>
                        <ul>
                            <li>Account: <strong>sb-9we9k30933294@personal.example.com</strong></li>
                            <li>Password: <strong>4tP&j^$8</strong></li>
                        </ul>
                        <p>Use these credentials when prompted during the PayPal login process. Note that these accounts are for testing purposes only and do not represent real financial transactions.</p>
                    </div>                    
                {% else %}
                    <h2>Add Shipping Address</h2>
                    <br>
                    <form id="shippingAddressForm">
                        <div class="form-group mb-3">
                            <input type="text" class="form-control" id="recipient_name" placeholder="Recipient Name" required>
                        </div>
                        <div class="form-group mb-3">
                            <input type="text" class="form-control" id="full_address" placeholder="Address" required>
                        </div>
                        <div class="form-group mb-3">
                            <input type="text" class="form-control" id="city" placeholder="City" required>
                        </div>
                        <div class="form-group mb-3">
                            <input type="text" class="form-control" id="zip_code" placeholder="Zip Code" required>
                        </div>
                        <div class="form-group mb-3">
                            <input type="text" class="form-control" id="country" placeholder="Country" required>
                        </div>
                        <div class="text-center">
                            <button type="button" class="btn btn-outline-secondary btn-lg" id="saveAddressButton">Save Address</button>
                        </div>
                    </form>                                        
                {% endif %}
            {% else %}
                <div class="alert alert-warning">
                    <p>Please <a href="{% url 'store:login' %}">login</a> or <a href="{% url 'store:register' %}">register</a> to proceed with your order.</p>
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}














store/templates/store/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Duckyware</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Rowdies:wght@300;400;700&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'store/css/general.css' %}">
    <link rel="stylesheet" href="{% static 'store/css/layout.css' %}">
    <link rel="stylesheet" href="{% static 'store/css/home.css' %}">
    <link rel="stylesheet" href="{% static 'store/css/category_search.css' %}">
    <link rel="stylesheet" href="{% static 'store/css/product_view.css' %}">
    <link rel="stylesheet" href="{% static 'store/css/cart.css' %}">
    <link rel="stylesheet" href="{% static 'store/css/checkout.css' %}">
    <!-- Images -->
    <link rel="icon" type="image/x-icon" href="{% static 'store/images/cs50_logo.ico' %}">
</head>
<body>
    <header>
        <!-- topbar -->
        <div class="top-bar">
            <form action="{% url 'store:search' %}" method="GET" class="search-container">
                <input type="text" name="query" placeholder="Search..." required>
                <button type="submit"><img src="{% static 'store/images/search-icon.svg' %}" alt="Search"></button>
            </form>
            <div class="icon-container">
                {% if user.is_authenticated %}
                    <div class="user-icon-container">
                        <a href="{% url 'store:profile' %}">
                            <img src="{% static 'store/images/user-icon.svg' %}" alt="Profile">
                            <span class="user-name">{{ user.username }}</span>
                        </a>
                        <div class="user-dropdown">
                            <a href="{% url 'store:profile' %}">Profile</a>
                            <a href="{% url 'store:wishlist' %}">Wishlist</a>
                            <a href="{% url 'store:orders' %}">Orders</a>
                            <a href="{% url 'store:logout' %}">Logout</a>
                            {% if user.is_staff or user.is_superuser %}
                                <!-- enter to admin panel -->
                                <a href="{% url 'admin:index' %}">Admin Panel</a>
                            {% endif %}
                        </div>
                    </div>
                {% else %}
                    <a href="{% url 'store:login' %}">
                        <img src="{% static 'store/images/user-icon.svg' %}" alt="Sign In">
                        <span class="sign-in-register">Sign In / Register</span>
                    </a>
                {% endif %}
            </div>
            <div class="cart-container">
                <a href="{% url 'store:cart' %}">
                    <img src="{% static 'store/images/cart-icon.svg' %}" alt="Cart">
                    <span class="cart-text">{{ cart_items }} items - ${{ cart_total }}</span>
                </a>
            </div>
        </div>              
        <h1 class="title"><a href="{% url 'store:home' %}" class="site-title">DUCKYWARE</a></h1>
    </header>
    

    <!-- category navbar -->
    <nav>
        <ul class="nav-menu">
            {% for category in categories %}
                {% if not category.parent %}
                    <li class="nav-item">
                        <a href="{% url 'store:category' category.name %}">{{ category.name }}</a>
                        {% if category.children.all %}
                            <ul class="submenu">
                                {% for subcategory in category.children.all %}
                                    <li>
                                        <a href="{% url 'store:category' subcategory.name %}">{{ subcategory.name }}</a>
                                        {% if subcategory.children.all %}
                                            <ul class="submenu">
                                                {% for subsubcategory in subcategory.children.all %}
                                                    <li><a href="{% url 'store:category' subsubcategory.name %}">{{ subsubcategory.name }}</a></li>
                                                {% endfor %}
                                            </ul>
                                        {% endif %}
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>
    
    <main>
        {% block content %}

        {% endblock %}
    </main>

    <footer>
        <div class="footer-content">
            <p>&copy; 2024 Duckyware. All rights reserved.</p>
            <p>This project is created by Raúl Estevez for the final project of <br>"CS50's Web Programming with Python and JavaScript" offered by HarvardX.</p>
            <p>Find me on <a href="https://www.linkedin.com/in/raulesteveza/" target="_blank">LinkedIn</a>.</p>
            <p>
                <a href="#">Privacy Policy</a> | 
                <a href="#">Terms of Service</a>
            </p>
        </div>
    </footer>
</body>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- SweetAlert JS -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- Custom JS -->
    <script src="{% static 'store/js/javascript.js' %}"></script>
</html>




store/templates/store/login.html
{% extends 'store/layout.html' %}

{% block content %}
  <div class="d-flex justify-content-center align-items-center" style="min-height: 70vh;">
        <div class="w-100" style="max-width: 400px;">
            {% if message %}
                <div class="alert alert-warning" role="alert">
                    {{ message }}
                </div>
            {% endif %}
            
            <form action="{% url 'store:login' %}" method="post" class="form-signin">
                <!-- security -->
                {% csrf_token %}
                <!-- login containers -->
                <h1 class="h3 mb-3 fw-bolt text-center">Login</h1>
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="usernameInput" name="username" placeholder="Username" required>
                    <label for="usernameInput">Username</label>
                </div>
                
                <div class="form-floating mb-3">
                    <input type="password" class="form-control" id="passwordInput" name="password" placeholder="Password" required>
                    <label for="passwordInput">Password</label>
                </div>
                <button class="btn btn-outline-secondary w-100" type="submit">Login</button>
                <p class="mt-2">Don't have an account? <a href="{% url 'store:register' %}">Register here.</a></p>
            </form>
        </div>
    </div>
{% endblock %}

store/templates/store/order_detail.html
{% extends 'store/layout.html' %}
{% load custom_filters %}

{% block content %}
<div class="container mt-4 mb-4">
    <div class="row">
        <div class="col-md-12">
            <h2>Order Details</h2>
            <br>
            <p><strong>Order Number:</strong> {{ order.id }}</p>
            <p><strong>Date:</strong> {{ order.created_at|date:"Y-m-d H:i" }}</p>
            <p><strong>Payment Method:</strong> {{ order.get_payment_method_display }}</p>
            <p><strong>Status:</strong> {{ order.get_status_display }}</p>
            
            {% if order.payment_method == 'TRANSFER' %}
            <p><strong>Bank Account Number:</strong> {{ order.bank_account_number }}</p>
            {% endif %}
            <br>
            <h3>Items</h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in order_items %}
                    <tr onclick="window.location='{% url 'store:product_view' category_name=item.content_object.category.name product_id=item.content_object.id %}'" style="cursor: pointer;">
                        <td>{{ item.content_object.title }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>${{ item.price_at_purchase }}</td>
                        <td>${{ item.quantity|multiply:item.price_at_purchase }}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="3" class="text-end"><strong><h4>Total:</h4></strong></td>
                        <td><h5>${{ order_items|sum_subtotals }}</h5></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}




store/templates/store/orders.html
{% extends 'store/layout.html' %}

{% block content %}
<div class="container mt-4 mb-4">
    <div class="row">
        <div class="col-md-12">
            <h2>Your Orders</h2>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Order Number</th>
                        <th>Date</th>
                        <th>Payment Method</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                    <tr onclick="window.location='{% url 'store:order_detail' order.id %}'" style="cursor: pointer;">
                        <td>{{ order.id }}</td>
                        <td>{{ order.created_at|date:"Y-m-d H:i" }}</td>
                        <td>{{ order.get_payment_method_display }}</td>
                        <td>{{ order.get_status_display }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}





store/templates/store/payment_error.html
{% extends 'store/layout.html' %}

{% block content %}
<div class="container mt-4">
    <h1>Payment Error</h1>
    <br>
    <p>There was an error processing your payment: {{ error.message }}</p>
    <div class="text-center mt-4">
        <a href="{% url 'store:home' %}" class="btn btn-outline-secondary btn-lg">Return to Home Page</a>
    </div>
</div>
{% endblock %}


store/templates/store/transfer.html
{% extends 'store/layout.html' %}

{% block content %}
<div class="container mt-4 mb-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h2>Transfer Payment Instructions</h2>
            <br>
            <p>Please transfer the amount to the following bank account:</p>
            <p><strong>Bank Account Number:</strong> 1234567890</p>
            <p>Make sure to include the following order number in the payment reference:</p>
            <p><strong>Order Number:</strong> {{ order.id }}</p>
            <p>Once the transfer is complete, please allow some time for the payment to be confirmed.</p>
            <div class="text-center">
                <a href="{% url 'store:orders' %}" class="btn btn-outline-secondary btn-lg mt-4">View Orders</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}
